# Generated by Django 4.2.7 on 2023-12-12 17:46

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cats',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('sex', models.CharField(choices=[('MALE', 'male'), ('FEMALE', 'female')], max_length=255)),
                ('image', models.ImageField(upload_to='cats')),
                ('birthplace', models.CharField(max_length=100)),
                ('birthdate', models.DateTimeField()),
                ('race', models.CharField(max_length=255)),
                ('is_adult', models.BooleanField(default=False)),
                ('linkPedigree', models.CharField(max_length=255)),
            ],
        ),
    ]
