# Generated by Django 4.2.7 on 2023-12-12 18:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cats', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Cats',
            new_name='Cat',
        ),
        migrations.RenameField(
            model_name='cat',
            old_name='birthdate',
            new_name='birth_date',
        ),
        migrations.RenameField(
            model_name='cat',
            old_name='birthplace',
            new_name='birth_place',
        ),
    ]
