# Generated by Django 5.0 on 2023-12-13 18:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cats', '0002_rename_cats_cat_rename_birthdate_cat_birth_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cat',
            name='birth_date',
            field=models.DateField(),
        ),
    ]
