# Generated by Django 5.0 on 2023-12-13 18:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cats', '0003_alter_cat_birth_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cat',
            name='sex',
            field=models.CharField(choices=[('MACHO', 'macho'), ('HEMBRA', 'hembra')], max_length=255),
        ),
    ]
